name: talker_persistent
description: An extension for the talker package that adds persistence to logs, allowing you to save logs both to files and Hive database.
version: 2.0.0+3
repository: https://github.com/eduardohr-muniz/talker_persistent
homepage: https://github.com/eduardohr-muniz/talker_persistent
issue_tracker: https://github.com/eduardohr-muniz/talker_persistent/issues

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  talker: ^5.0.0
  path: ^1.9.0
  hive_ce: any
  collection: any
  talker_dio_logger: any

dev_dependencies:
  build_runner: ^2.4.15
  hive_ce_generator: ^1.9.2
  lints: ^5.0.0
  test: ^1.24.0
